// PDF Report Generator Service using jsPDF
import { jsPDF } from 'jspdf';
import { CenterSettings } from '../../../types';
import { storageService } from '../../../services/storageService';
import { formatINR } from '../../../lib/formatters';

export function downloadStudentReportPDF(
  metrics: {
    total: number;
    active: number;
    newAdmissions: number;
    onHold: number;
    inactive: number;
    discontinued: number;
  },
  batchData: Array<{
    batchName: string;
    trainer: string;
    capacity: number;
    enrolled: number;
    pct: number;
    spotsAvailable: number;
  }>,
  dateRangeLabel: string
) {
  const settings: CenterSettings = storageService.getSettings();
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 16;

  // Header Banner
  doc.setFillColor(180, 60, 20); // brand-700
  doc.rect(14, y, pageWidth - 28, 22, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(settings.centerName.toUpperCase(), 20, y + 8);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('STUDENT ENROLLMENT & DEMOGRAPHICS REPORT', 20, y + 14);
  doc.text(`Period: ${dateRangeLabel}`, pageWidth - 20, y + 14, { align: 'right' });

  y += 28;

  // Summary KPI Table
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Executive Membership Summary', 14, y);
  y += 5;

  const kpis = [
    ['Total Enrolled', String(metrics.total)],
    ['Active Members', String(metrics.active)],
    ['New Admissions', String(metrics.newAdmissions)],
    ['On-Hold / Paused', String(metrics.onHold)],
    ['Inactive Members', String(metrics.inactive)],
    ['Discontinued / Left', String(metrics.discontinued)],
  ];

  doc.setFillColor(248, 250, 252);
  doc.rect(14, y, pageWidth - 28, 20, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.rect(14, y, pageWidth - 28, 20, 'S');

  const colWidth = (pageWidth - 28) / 3;
  kpis.forEach((kpi, idx) => {
    const col = idx % 3;
    const row = Math.floor(idx / 3);
    const kpiX = 18 + col * colWidth;
    const kpiY = y + 6 + row * 9;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(kpi[0] + ':', kpiX, kpiY);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(15, 23, 42);
    doc.text(kpi[1], kpiX + 36, kpiY);
  });

  y += 28;

  // Batch-Wise Capacity Table
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Batch Distribution & Occupancy', 14, y);
  y += 6;

  // Table Headers
  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, pageWidth - 28, 7, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(71, 85, 105);

  doc.text('Batch Name', 18, y + 4.5);
  doc.text('Trainer', 70, y + 4.5);
  doc.text('Capacity', 115, y + 4.5, { align: 'right' });
  doc.text('Enrolled', 140, y + 4.5, { align: 'right' });
  doc.text('Occupancy', 165, y + 4.5, { align: 'right' });
  doc.text('Available', 190, y + 4.5, { align: 'right' });

  y += 7;

  // Rows
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(15, 23, 42);

  batchData.forEach(b => {
    doc.setDrawColor(241, 245, 249);
    doc.line(14, y + 6, pageWidth - 14, y + 6);

    doc.text(b.batchName, 18, y + 4.5);
    doc.text(b.trainer, 70, y + 4.5);
    doc.text(String(b.capacity), 115, y + 4.5, { align: 'right' });
    doc.text(String(b.enrolled), 140, y + 4.5, { align: 'right' });
    doc.text(`${b.pct}%`, 165, y + 4.5, { align: 'right' });
    doc.text(String(b.spotsAvailable), 190, y + 4.5, { align: 'right' });

    y += 7;
  });

  y += 15;

  // Footer
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(148, 163, 184);
  doc.text(
    `Generated by ${settings.centerName} ERP System on ${new Date().toLocaleString('en-IN')}`,
    14,
    285
  );

  doc.save(`Student_Enrollment_Report_${new Date().toISOString().split('T')[0]}.pdf`);
}

export function downloadFinancialReportPDF(
  financials: {
    grossBilled: number;
    netCollected: number;
    totalExpense: number;
    netProfit: number;
    collectionRate: number;
  },
  paymentMethods: Array<[string, number]>,
  expenseCategories: Array<[string, number]>,
  dateRangeLabel: string
) {
  const settings: CenterSettings = storageService.getSettings();
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 16;

  // Header Banner
  doc.setFillColor(15, 118, 110); // teal-700
  doc.rect(14, y, pageWidth - 28, 22, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(settings.centerName.toUpperCase(), 20, y + 8);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('FINANCIAL HEALTH & P&L OPERATING STATEMENT', 20, y + 14);
  doc.text(`Period: ${dateRangeLabel}`, pageWidth - 20, y + 14, { align: 'right' });

  y += 28;

  // Financial Health KPIs
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Financial Health Overview', 14, y);
  y += 5;

  const kpis = [
    ['Gross Billed Value', `Rs. ${Math.round(financials.grossBilled).toLocaleString('en-IN')}`],
    ['Net Fee Collected', `Rs. ${Math.round(financials.netCollected).toLocaleString('en-IN')} (${financials.collectionRate}%)`],
    ['Operating Expenses', `Rs. ${Math.round(financials.totalExpense).toLocaleString('en-IN')}`],
    ['Net Operating Surplus', `Rs. ${Math.round(financials.netProfit).toLocaleString('en-IN')}`],
  ];

  doc.setFillColor(248, 250, 252);
  doc.rect(14, y, pageWidth - 28, 16, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.rect(14, y, pageWidth - 28, 16, 'S');

  const colWidth = (pageWidth - 28) / 2;
  kpis.forEach((kpi, idx) => {
    const col = idx % 2;
    const row = Math.floor(idx / 2);
    const kpiX = 18 + col * colWidth;
    const kpiY = y + 6 + row * 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(100, 116, 139);
    doc.text(kpi[0] + ':', kpiX, kpiY);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(15, 23, 42);
    doc.text(kpi[1], kpiX + 46, kpiY);
  });

  y += 24;

  // Payment Collections
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Collections by Payment Channel', 14, y);
  y += 6;

  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, pageWidth - 28, 7, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text('Payment Method', 18, y + 4.5);
  doc.text('Amount Collected', pageWidth - 20, y + 4.5, { align: 'right' });
  y += 7;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(15, 23, 42);
  paymentMethods.forEach(([method, amt]) => {
    doc.setDrawColor(241, 245, 249);
    doc.line(14, y + 6, pageWidth - 14, y + 6);
    doc.text(method, 18, y + 4.5);
    doc.text(`Rs. ${Math.round(amt).toLocaleString('en-IN')}`, pageWidth - 20, y + 4.5, { align: 'right' });
    y += 7;
  });

  y += 10;

  // Operating Expenses
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Operating Expenses Breakdown', 14, y);
  y += 6;

  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, pageWidth - 28, 7, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text('Expense Category', 18, y + 4.5);
  doc.text('Amount (INR)', pageWidth - 20, y + 4.5, { align: 'right' });
  y += 7;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(15, 23, 42);
  expenseCategories.forEach(([cat, amt]) => {
    doc.setDrawColor(241, 245, 249);
    doc.line(14, y + 6, pageWidth - 14, y + 6);
    doc.text(cat, 18, y + 4.5);
    doc.text(`Rs. ${Math.round(amt).toLocaleString('en-IN')}`, pageWidth - 20, y + 4.5, { align: 'right' });
    y += 7;
  });

  // Footer
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(148, 163, 184);
  doc.text(
    `Generated by ${settings.centerName} ERP System on ${new Date().toLocaleString('en-IN')}`,
    14,
    285
  );

  doc.save(`Financial_PL_Report_${new Date().toISOString().split('T')[0]}.pdf`);
}
